name: Bump version

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Select the version to increment.'
        required: true
        default: 'prerelease'
        type: choice
        options:
          - prerelease
          - patch
          - minor
          - major

jobs:
  bump-version:
    name: 'Bump version'
    runs-on: linux
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # Needs to be created
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Git User
        run: |
          git config --local user.email "${GITHUB_ACTOR}"
          git config --local user.name "${GITHUB_ACTOR}"
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Yarn
        run: npm install --global yarn
      - name: Sync local tags with remote
        run: git fetch --prune --prune-tags
      - name: Bump version in package.json and tag
        run: yarn version --${{ inputs.version_type }}
      - name: Push changes back to remote
        run: |
          git push
          git push --tags
      - name: Set variables
        id: vars
        run: |
          echo ::set-output name=release_name::"v$(jq -r ".version" package.json)"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.release_name }}
          release_name: ${{ steps.vars.outputs.release_name }}
          draft: false
          prerelease: false
